-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 13:03:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdescuadron
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdescuadron
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdescuadron` DEFAULT CHARACTER SET utf8 ;
USE `bdescuadron` ;

-- -----------------------------------------------------
-- Table `bdescuadron`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `ImagenUrl` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`ordenes` (
  `idOrdenes` INT(11) NOT NULL AUTO_INCREMENT,
  `FechaOrden` DATE NOT NULL,
  `FechaRequerida` DATE NOT NULL,
  `FechaEnvio` DATE NOT NULL,
  `Usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idOrdenes`),
  INDEX `fk_Ordenes_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Ordenes_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `bdescuadron`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`empresa` (
  `idEmpresa` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `SitioWeb` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`productos` (
  `idProductos` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreProducto` VARCHAR(45) NOT NULL,
  `PrecioUnidad` DECIMAL(10,0) NOT NULL,
  `UnidadEnStock` INT(11) NOT NULL,
  `UnidadesEnOrden` INT(11) NOT NULL,
  `Categoria_idCategoria` INT(11) NOT NULL,
  `Empresa_idEmpresa` INT(11) NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedor1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `bdescuadron`.`categoria` (`idCategoria`),
  CONSTRAINT `fk_Productos_Proveedor1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `bdescuadron`.`empresa` (`idEmpresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`detallesordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`detallesordenes` (
  `PrecioUnidad` DECIMAL(10,0) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `Descuento` DECIMAL(10,0) NOT NULL,
  `Productos_idProductos` INT(11) NOT NULL,
  `Ordenes_idOrdenes` INT(11) NOT NULL,
  PRIMARY KEY (`Ordenes_idOrdenes`, `Productos_idProductos`),
  INDEX `fk_DetallesOrdenes_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_DetallesOrdenes_Ordenes1_idx` (`Ordenes_idOrdenes` ASC) VISIBLE,
  CONSTRAINT `fk_DetallesOrdenes_Ordenes1`
    FOREIGN KEY (`Ordenes_idOrdenes`)
    REFERENCES `bdescuadron`.`ordenes` (`idOrdenes`),
  CONSTRAINT `fk_DetallesOrdenes_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `bdescuadron`.`productos` (`idProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`Direcciones` (
  `idDirecciones` INT(11) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDirecciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`tipopublicidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`tipopublicidad` (
  `idTipoPublicidad` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoPublicidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`publicidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`publicidad` (
  `idPublicidad` INT(11) NOT NULL AUTO_INCREMENT,
  `DestinoDeImagen` VARCHAR(500) NOT NULL,
  `Costo` DECIMAL(10,0) NOT NULL,
  `TipoPublicidad_idTipoPublicidad` INT(11) NOT NULL,
  `Empresa_idProveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idPublicidad`),
  INDEX `fk_Publicidad_TipoPublicidad_idx` (`TipoPublicidad_idTipoPublicidad` ASC) VISIBLE,
  INDEX `fk_Publicidad_Empresa1_idx` (`Empresa_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Publicidad_Empresa1`
    FOREIGN KEY (`Empresa_idProveedor`)
    REFERENCES `bdescuadron`.`empresa` (`idEmpresa`),
  CONSTRAINT `fk_Publicidad_TipoPublicidad`
    FOREIGN KEY (`TipoPublicidad_idTipoPublicidad`)
    REFERENCES `bdescuadron`.`tipopublicidad` (`idTipoPublicidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdescuadron`.`UsuariosDirecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdescuadron`.`UsuariosDirecciones` (
  `usuario_idUsuario` INT(11) NOT NULL,
  `Direcciones_idDirecciones` INT(11) NOT NULL,
  INDEX `fk_UsuariosDirecciones_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_UsuariosDirecciones_Direcciones1_idx` (`Direcciones_idDirecciones` ASC) VISIBLE,
  CONSTRAINT `fk_UsuariosDirecciones_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `bdescuadron`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuariosDirecciones_Direcciones1`
    FOREIGN KEY (`Direcciones_idDirecciones`)
    REFERENCES `bdescuadron`.`Direcciones` (`idDirecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
